/*
 * Twilio
 * Enabling phones, VoIP, and messaging to be embedded into web, desktop, and mobile software.
 *
 * OpenAPI spec version: 2010-04-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.xgp.hub.twilio.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import javax.validation.constraints.*;

/** Account */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaJerseyDIServerCodegen",
    date = "2020-05-22T20:43:20.517+02:00[Europe/Paris]")
public class Account {
  @JsonProperty("auth_token")
  private String authToken = null;

  @JsonProperty("date_created")
  private String dateCreated = null;

  @JsonProperty("date_updated")
  private String dateUpdated = null;

  @JsonProperty("friendly_name")
  private String friendlyName = null;

  @JsonProperty("sid")
  private String sid = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("subresource_uris")
  private Object subresourceUris = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("uri")
  private String uri = null;

  public Account authToken(String authToken) {
    this.authToken = authToken;
    return this;
  }

  /**
   * Get authToken
   *
   * @return authToken
   */
  @JsonProperty("auth_token")
  @Schema(description = "")
  public String getAuthToken() {
    return authToken;
  }

  public void setAuthToken(String authToken) {
    this.authToken = authToken;
  }

  public Account dateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * The date that this account was created, in GMT in RFC 2822 format
   *
   * @return dateCreated
   */
  @JsonProperty("date_created")
  @Schema(description = "The date that this account was created, in GMT in RFC 2822 format")
  public String getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
  }

  public Account dateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
    return this;
  }

  /**
   * The date that this account was last updated, in GMT in RFC 2822 format.
   *
   * @return dateUpdated
   */
  @JsonProperty("date_updated")
  @Schema(description = "The date that this account was last updated, in GMT in RFC 2822 format.")
  public String getDateUpdated() {
    return dateUpdated;
  }

  public void setDateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
  }

  public Account friendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
    return this;
  }

  /**
   * A human readable description of this account, up to 64 characters long. By default the
   * FriendlyName is your email address.
   *
   * @return friendlyName
   */
  @JsonProperty("friendly_name")
  @Schema(
      description =
          "A human readable description of this account, up to 64 characters long. By default the FriendlyName is your email address.")
  public String getFriendlyName() {
    return friendlyName;
  }

  public void setFriendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
  }

  public Account sid(String sid) {
    this.sid = sid;
    return this;
  }

  /**
   * A 34 character string that uniquely identifies this account.
   *
   * @return sid
   */
  @JsonProperty("sid")
  @Schema(description = "A 34 character string that uniquely identifies this account.")
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public Account status(String status) {
    this.status = status;
    return this;
  }

  /**
   * The status of this account. Usually active, but can be suspended or closed.
   *
   * @return status
   */
  @JsonProperty("status")
  @Schema(
      description = "The status of this account. Usually active, but can be suspended or closed.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Account subresourceUris(Object subresourceUris) {
    this.subresourceUris = subresourceUris;
    return this;
  }

  /**
   * Get subresourceUris
   *
   * @return subresourceUris
   */
  @JsonProperty("subresource_uris")
  @Schema(description = "")
  public Object getSubresourceUris() {
    return subresourceUris;
  }

  public void setSubresourceUris(Object subresourceUris) {
    this.subresourceUris = subresourceUris;
  }

  public Account type(String type) {
    this.type = type;
    return this;
  }

  /**
   * The type of this account. Either Trial or Full if you&#x27;ve upgraded.
   *
   * @return type
   */
  @JsonProperty("type")
  @Schema(description = "The type of this account. Either Trial or Full if you've upgraded.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Account uri(String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   *
   * @return uri
   */
  @JsonProperty("uri")
  @Schema(description = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.authToken, account.authToken)
        && Objects.equals(this.dateCreated, account.dateCreated)
        && Objects.equals(this.dateUpdated, account.dateUpdated)
        && Objects.equals(this.friendlyName, account.friendlyName)
        && Objects.equals(this.sid, account.sid)
        && Objects.equals(this.status, account.status)
        && Objects.equals(this.subresourceUris, account.subresourceUris)
        && Objects.equals(this.type, account.type)
        && Objects.equals(this.uri, account.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        authToken, dateCreated, dateUpdated, friendlyName, sid, status, subresourceUris, type, uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");

    sb.append("    authToken: ").append(toIndentedString(authToken)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateUpdated: ").append(toIndentedString(dateUpdated)).append("\n");
    sb.append("    friendlyName: ").append(toIndentedString(friendlyName)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    subresourceUris: ").append(toIndentedString(subresourceUris)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
