/*
 * Twilio
 * Enabling phones, VoIP, and messaging to be embedded into web, desktop, and mobile software.
 *
 * OpenAPI spec version: 2010-04-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.xgp.hub.twilio.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import javax.validation.constraints.*;

/** Domain */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaJerseyDIServerCodegen",
    date = "2020-05-22T20:43:20.517+02:00[Europe/Paris]")
public class Domain {
  @JsonProperty("account_sid")
  private String accountSid = null;

  @JsonProperty("api_version")
  private String apiVersion = null;

  @JsonProperty("auth_type")
  private String authType = null;

  @JsonProperty("date_created")
  private String dateCreated = null;

  @JsonProperty("date_updated")
  private String dateUpdated = null;

  @JsonProperty("domain_name")
  private String domainName = null;

  @JsonProperty("friendly_name")
  private String friendlyName = null;

  @JsonProperty("sid")
  private String sid = null;

  @JsonProperty("subresource_uris")
  private Object subresourceUris = null;

  @JsonProperty("uri")
  private String uri = null;

  @JsonProperty("voice_fallback_method")
  private String voiceFallbackMethod = null;

  @JsonProperty("voice_fallback_url")
  private Object voiceFallbackUrl = null;

  @JsonProperty("voice_method")
  private String voiceMethod = null;

  @JsonProperty("voice_status_callback_method")
  private String voiceStatusCallbackMethod = null;

  @JsonProperty("voice_status_callback_url")
  private Object voiceStatusCallbackUrl = null;

  @JsonProperty("voice_url")
  private String voiceUrl = null;

  public Domain accountSid(String accountSid) {
    this.accountSid = accountSid;
    return this;
  }

  /**
   * Get accountSid
   *
   * @return accountSid
   */
  @JsonProperty("account_sid")
  @Schema(description = "")
  public String getAccountSid() {
    return accountSid;
  }

  public void setAccountSid(String accountSid) {
    this.accountSid = accountSid;
  }

  public Domain apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

  /**
   * Get apiVersion
   *
   * @return apiVersion
   */
  @JsonProperty("api_version")
  @Schema(description = "")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public Domain authType(String authType) {
    this.authType = authType;
    return this;
  }

  /**
   * Get authType
   *
   * @return authType
   */
  @JsonProperty("auth_type")
  @Schema(description = "")
  public String getAuthType() {
    return authType;
  }

  public void setAuthType(String authType) {
    this.authType = authType;
  }

  public Domain dateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * Get dateCreated
   *
   * @return dateCreated
   */
  @JsonProperty("date_created")
  @Schema(description = "")
  public String getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
  }

  public Domain dateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
    return this;
  }

  /**
   * Get dateUpdated
   *
   * @return dateUpdated
   */
  @JsonProperty("date_updated")
  @Schema(description = "")
  public String getDateUpdated() {
    return dateUpdated;
  }

  public void setDateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
  }

  public Domain domainName(String domainName) {
    this.domainName = domainName;
    return this;
  }

  /**
   * Get domainName
   *
   * @return domainName
   */
  @JsonProperty("domain_name")
  @Schema(description = "")
  public String getDomainName() {
    return domainName;
  }

  public void setDomainName(String domainName) {
    this.domainName = domainName;
  }

  public Domain friendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
    return this;
  }

  /**
   * Get friendlyName
   *
   * @return friendlyName
   */
  @JsonProperty("friendly_name")
  @Schema(description = "")
  public String getFriendlyName() {
    return friendlyName;
  }

  public void setFriendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
  }

  public Domain sid(String sid) {
    this.sid = sid;
    return this;
  }

  /**
   * Get sid
   *
   * @return sid
   */
  @JsonProperty("sid")
  @Schema(description = "")
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public Domain subresourceUris(Object subresourceUris) {
    this.subresourceUris = subresourceUris;
    return this;
  }

  /**
   * Get subresourceUris
   *
   * @return subresourceUris
   */
  @JsonProperty("subresource_uris")
  @Schema(description = "")
  public Object getSubresourceUris() {
    return subresourceUris;
  }

  public void setSubresourceUris(Object subresourceUris) {
    this.subresourceUris = subresourceUris;
  }

  public Domain uri(String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   *
   * @return uri
   */
  @JsonProperty("uri")
  @Schema(description = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public Domain voiceFallbackMethod(String voiceFallbackMethod) {
    this.voiceFallbackMethod = voiceFallbackMethod;
    return this;
  }

  /**
   * Get voiceFallbackMethod
   *
   * @return voiceFallbackMethod
   */
  @JsonProperty("voice_fallback_method")
  @Schema(description = "")
  public String getVoiceFallbackMethod() {
    return voiceFallbackMethod;
  }

  public void setVoiceFallbackMethod(String voiceFallbackMethod) {
    this.voiceFallbackMethod = voiceFallbackMethod;
  }

  public Domain voiceFallbackUrl(Object voiceFallbackUrl) {
    this.voiceFallbackUrl = voiceFallbackUrl;
    return this;
  }

  /**
   * Get voiceFallbackUrl
   *
   * @return voiceFallbackUrl
   */
  @JsonProperty("voice_fallback_url")
  @Schema(description = "")
  public Object getVoiceFallbackUrl() {
    return voiceFallbackUrl;
  }

  public void setVoiceFallbackUrl(Object voiceFallbackUrl) {
    this.voiceFallbackUrl = voiceFallbackUrl;
  }

  public Domain voiceMethod(String voiceMethod) {
    this.voiceMethod = voiceMethod;
    return this;
  }

  /**
   * Get voiceMethod
   *
   * @return voiceMethod
   */
  @JsonProperty("voice_method")
  @Schema(description = "")
  public String getVoiceMethod() {
    return voiceMethod;
  }

  public void setVoiceMethod(String voiceMethod) {
    this.voiceMethod = voiceMethod;
  }

  public Domain voiceStatusCallbackMethod(String voiceStatusCallbackMethod) {
    this.voiceStatusCallbackMethod = voiceStatusCallbackMethod;
    return this;
  }

  /**
   * Get voiceStatusCallbackMethod
   *
   * @return voiceStatusCallbackMethod
   */
  @JsonProperty("voice_status_callback_method")
  @Schema(description = "")
  public String getVoiceStatusCallbackMethod() {
    return voiceStatusCallbackMethod;
  }

  public void setVoiceStatusCallbackMethod(String voiceStatusCallbackMethod) {
    this.voiceStatusCallbackMethod = voiceStatusCallbackMethod;
  }

  public Domain voiceStatusCallbackUrl(Object voiceStatusCallbackUrl) {
    this.voiceStatusCallbackUrl = voiceStatusCallbackUrl;
    return this;
  }

  /**
   * Get voiceStatusCallbackUrl
   *
   * @return voiceStatusCallbackUrl
   */
  @JsonProperty("voice_status_callback_url")
  @Schema(description = "")
  public Object getVoiceStatusCallbackUrl() {
    return voiceStatusCallbackUrl;
  }

  public void setVoiceStatusCallbackUrl(Object voiceStatusCallbackUrl) {
    this.voiceStatusCallbackUrl = voiceStatusCallbackUrl;
  }

  public Domain voiceUrl(String voiceUrl) {
    this.voiceUrl = voiceUrl;
    return this;
  }

  /**
   * Get voiceUrl
   *
   * @return voiceUrl
   */
  @JsonProperty("voice_url")
  @Schema(description = "")
  public String getVoiceUrl() {
    return voiceUrl;
  }

  public void setVoiceUrl(String voiceUrl) {
    this.voiceUrl = voiceUrl;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Domain domain = (Domain) o;
    return Objects.equals(this.accountSid, domain.accountSid)
        && Objects.equals(this.apiVersion, domain.apiVersion)
        && Objects.equals(this.authType, domain.authType)
        && Objects.equals(this.dateCreated, domain.dateCreated)
        && Objects.equals(this.dateUpdated, domain.dateUpdated)
        && Objects.equals(this.domainName, domain.domainName)
        && Objects.equals(this.friendlyName, domain.friendlyName)
        && Objects.equals(this.sid, domain.sid)
        && Objects.equals(this.subresourceUris, domain.subresourceUris)
        && Objects.equals(this.uri, domain.uri)
        && Objects.equals(this.voiceFallbackMethod, domain.voiceFallbackMethod)
        && Objects.equals(this.voiceFallbackUrl, domain.voiceFallbackUrl)
        && Objects.equals(this.voiceMethod, domain.voiceMethod)
        && Objects.equals(this.voiceStatusCallbackMethod, domain.voiceStatusCallbackMethod)
        && Objects.equals(this.voiceStatusCallbackUrl, domain.voiceStatusCallbackUrl)
        && Objects.equals(this.voiceUrl, domain.voiceUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        accountSid,
        apiVersion,
        authType,
        dateCreated,
        dateUpdated,
        domainName,
        friendlyName,
        sid,
        subresourceUris,
        uri,
        voiceFallbackMethod,
        voiceFallbackUrl,
        voiceMethod,
        voiceStatusCallbackMethod,
        voiceStatusCallbackUrl,
        voiceUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Domain {\n");

    sb.append("    accountSid: ").append(toIndentedString(accountSid)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateUpdated: ").append(toIndentedString(dateUpdated)).append("\n");
    sb.append("    domainName: ").append(toIndentedString(domainName)).append("\n");
    sb.append("    friendlyName: ").append(toIndentedString(friendlyName)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    subresourceUris: ").append(toIndentedString(subresourceUris)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    voiceFallbackMethod: ")
        .append(toIndentedString(voiceFallbackMethod))
        .append("\n");
    sb.append("    voiceFallbackUrl: ").append(toIndentedString(voiceFallbackUrl)).append("\n");
    sb.append("    voiceMethod: ").append(toIndentedString(voiceMethod)).append("\n");
    sb.append("    voiceStatusCallbackMethod: ")
        .append(toIndentedString(voiceStatusCallbackMethod))
        .append("\n");
    sb.append("    voiceStatusCallbackUrl: ")
        .append(toIndentedString(voiceStatusCallbackUrl))
        .append("\n");
    sb.append("    voiceUrl: ").append(toIndentedString(voiceUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
