/*
 * Twilio
 * Enabling phones, VoIP, and messaging to be embedded into web, desktop, and mobile software.
 *
 * OpenAPI spec version: 2010-04-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.xgp.hub.twilio.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import javax.validation.constraints.*;

/** Member */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaJerseyDIServerCodegen",
    date = "2020-05-22T20:43:20.517+02:00[Europe/Paris]")
public class Member {
  @JsonProperty("call_sid")
  private String callSid = null;

  @JsonProperty("date_enqueued")
  private String dateEnqueued = null;

  @JsonProperty("position")
  private Integer position = null;

  @JsonProperty("uri")
  private String uri = null;

  @JsonProperty("wait_time")
  private Integer waitTime = null;

  public Member callSid(String callSid) {
    this.callSid = callSid;
    return this;
  }

  /**
   * Get callSid
   *
   * @return callSid
   */
  @JsonProperty("call_sid")
  @Schema(description = "")
  public String getCallSid() {
    return callSid;
  }

  public void setCallSid(String callSid) {
    this.callSid = callSid;
  }

  public Member dateEnqueued(String dateEnqueued) {
    this.dateEnqueued = dateEnqueued;
    return this;
  }

  /**
   * Get dateEnqueued
   *
   * @return dateEnqueued
   */
  @JsonProperty("date_enqueued")
  @Schema(description = "")
  public String getDateEnqueued() {
    return dateEnqueued;
  }

  public void setDateEnqueued(String dateEnqueued) {
    this.dateEnqueued = dateEnqueued;
  }

  public Member position(Integer position) {
    this.position = position;
    return this;
  }

  /**
   * Get position
   *
   * @return position
   */
  @JsonProperty("position")
  @Schema(description = "")
  public Integer getPosition() {
    return position;
  }

  public void setPosition(Integer position) {
    this.position = position;
  }

  public Member uri(String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   *
   * @return uri
   */
  @JsonProperty("uri")
  @Schema(description = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public Member waitTime(Integer waitTime) {
    this.waitTime = waitTime;
    return this;
  }

  /**
   * Get waitTime
   *
   * @return waitTime
   */
  @JsonProperty("wait_time")
  @Schema(description = "")
  public Integer getWaitTime() {
    return waitTime;
  }

  public void setWaitTime(Integer waitTime) {
    this.waitTime = waitTime;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Member member = (Member) o;
    return Objects.equals(this.callSid, member.callSid)
        && Objects.equals(this.dateEnqueued, member.dateEnqueued)
        && Objects.equals(this.position, member.position)
        && Objects.equals(this.uri, member.uri)
        && Objects.equals(this.waitTime, member.waitTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callSid, dateEnqueued, position, uri, waitTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Member {\n");

    sb.append("    callSid: ").append(toIndentedString(callSid)).append("\n");
    sb.append("    dateEnqueued: ").append(toIndentedString(dateEnqueued)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    waitTime: ").append(toIndentedString(waitTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
