/*
 * Twilio
 * Enabling phones, VoIP, and messaging to be embedded into web, desktop, and mobile software.
 *
 * OpenAPI spec version: 2010-04-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.xgp.hub.twilio.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import javax.validation.constraints.*;

/** Message */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaJerseyDIServerCodegen",
    date = "2020-05-22T20:43:20.517+02:00[Europe/Paris]")
public class Message {
  @JsonProperty("account_sid")
  private String accountSid = null;

  @JsonProperty("api_version")
  private String apiVersion = null;

  @JsonProperty("body")
  private String body = null;

  @JsonProperty("date_created")
  private String dateCreated = null;

  @JsonProperty("date_sent")
  private String dateSent = null;

  @JsonProperty("date_updated")
  private String dateUpdated = null;

  @JsonProperty("direction")
  private String direction = null;

  @JsonProperty("from")
  private String from = null;

  @JsonProperty("num_media")
  private String numMedia = null;

  @JsonProperty("num_segments")
  private String numSegments = null;

  @JsonProperty("price")
  private String price = null;

  @JsonProperty("sid")
  private String sid = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("to")
  private String to = null;

  @JsonProperty("uri")
  private String uri = null;

  public Message accountSid(String accountSid) {
    this.accountSid = accountSid;
    return this;
  }

  /**
   * Get accountSid
   *
   * @return accountSid
   */
  @JsonProperty("account_sid")
  @Schema(description = "")
  public String getAccountSid() {
    return accountSid;
  }

  public void setAccountSid(String accountSid) {
    this.accountSid = accountSid;
  }

  public Message apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

  /**
   * Get apiVersion
   *
   * @return apiVersion
   */
  @JsonProperty("api_version")
  @Schema(description = "")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public Message body(String body) {
    this.body = body;
    return this;
  }

  /**
   * Get body
   *
   * @return body
   */
  @JsonProperty("body")
  @Schema(description = "")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public Message dateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * Get dateCreated
   *
   * @return dateCreated
   */
  @JsonProperty("date_created")
  @Schema(description = "")
  public String getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
  }

  public Message dateSent(String dateSent) {
    this.dateSent = dateSent;
    return this;
  }

  /**
   * Get dateSent
   *
   * @return dateSent
   */
  @JsonProperty("date_sent")
  @Schema(description = "")
  public String getDateSent() {
    return dateSent;
  }

  public void setDateSent(String dateSent) {
    this.dateSent = dateSent;
  }

  public Message dateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
    return this;
  }

  /**
   * Get dateUpdated
   *
   * @return dateUpdated
   */
  @JsonProperty("date_updated")
  @Schema(description = "")
  public String getDateUpdated() {
    return dateUpdated;
  }

  public void setDateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
  }

  public Message direction(String direction) {
    this.direction = direction;
    return this;
  }

  /**
   * Get direction
   *
   * @return direction
   */
  @JsonProperty("direction")
  @Schema(description = "")
  public String getDirection() {
    return direction;
  }

  public void setDirection(String direction) {
    this.direction = direction;
  }

  public Message from(String from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   *
   * @return from
   */
  @JsonProperty("from")
  @Schema(description = "")
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

  public Message numMedia(String numMedia) {
    this.numMedia = numMedia;
    return this;
  }

  /**
   * Get numMedia
   *
   * @return numMedia
   */
  @JsonProperty("num_media")
  @Schema(description = "")
  public String getNumMedia() {
    return numMedia;
  }

  public void setNumMedia(String numMedia) {
    this.numMedia = numMedia;
  }

  public Message numSegments(String numSegments) {
    this.numSegments = numSegments;
    return this;
  }

  /**
   * Get numSegments
   *
   * @return numSegments
   */
  @JsonProperty("num_segments")
  @Schema(description = "")
  public String getNumSegments() {
    return numSegments;
  }

  public void setNumSegments(String numSegments) {
    this.numSegments = numSegments;
  }

  public Message price(String price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   *
   * @return price
   */
  @JsonProperty("price")
  @Schema(description = "")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public Message sid(String sid) {
    this.sid = sid;
    return this;
  }

  /**
   * Get sid
   *
   * @return sid
   */
  @JsonProperty("sid")
  @Schema(description = "")
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public Message status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   *
   * @return status
   */
  @JsonProperty("status")
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Message to(String to) {
    this.to = to;
    return this;
  }

  /**
   * Get to
   *
   * @return to
   */
  @JsonProperty("to")
  @Schema(description = "")
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }

  public Message uri(String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   *
   * @return uri
   */
  @JsonProperty("uri")
  @Schema(description = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return Objects.equals(this.accountSid, message.accountSid)
        && Objects.equals(this.apiVersion, message.apiVersion)
        && Objects.equals(this.body, message.body)
        && Objects.equals(this.dateCreated, message.dateCreated)
        && Objects.equals(this.dateSent, message.dateSent)
        && Objects.equals(this.dateUpdated, message.dateUpdated)
        && Objects.equals(this.direction, message.direction)
        && Objects.equals(this.from, message.from)
        && Objects.equals(this.numMedia, message.numMedia)
        && Objects.equals(this.numSegments, message.numSegments)
        && Objects.equals(this.price, message.price)
        && Objects.equals(this.sid, message.sid)
        && Objects.equals(this.status, message.status)
        && Objects.equals(this.to, message.to)
        && Objects.equals(this.uri, message.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        accountSid,
        apiVersion,
        body,
        dateCreated,
        dateSent,
        dateUpdated,
        direction,
        from,
        numMedia,
        numSegments,
        price,
        sid,
        status,
        to,
        uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");

    sb.append("    accountSid: ").append(toIndentedString(accountSid)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateSent: ").append(toIndentedString(dateSent)).append("\n");
    sb.append("    dateUpdated: ").append(toIndentedString(dateUpdated)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    numMedia: ").append(toIndentedString(numMedia)).append("\n");
    sb.append("    numSegments: ").append(toIndentedString(numSegments)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
