/*
 * Twilio
 * Enabling phones, VoIP, and messaging to be embedded into web, desktop, and mobile software.
 *
 * OpenAPI spec version: 2010-04-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.xgp.hub.twilio.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import javax.validation.constraints.*;

/** Notification */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaJerseyDIServerCodegen",
    date = "2020-05-22T20:43:20.517+02:00[Europe/Paris]")
public class Notification {
  @JsonProperty("account_sid")
  private String accountSid = null;

  @JsonProperty("api_version")
  private String apiVersion = null;

  @JsonProperty("call_sid")
  private String callSid = null;

  @JsonProperty("date_created")
  private String dateCreated = null;

  @JsonProperty("date_updated")
  private String dateUpdated = null;

  @JsonProperty("error_code")
  private String errorCode = null;

  @JsonProperty("log")
  private String log = null;

  @JsonProperty("message_date")
  private String messageDate = null;

  @JsonProperty("message_text")
  private String messageText = null;

  @JsonProperty("more_info")
  private String moreInfo = null;

  @JsonProperty("request_method")
  private String requestMethod = null;

  @JsonProperty("request_url")
  private String requestUrl = null;

  @JsonProperty("request_variables")
  private String requestVariables = null;

  @JsonProperty("response_body")
  private String responseBody = null;

  @JsonProperty("response_headers")
  private String responseHeaders = null;

  @JsonProperty("sid")
  private String sid = null;

  @JsonProperty("uri")
  private String uri = null;

  public Notification accountSid(String accountSid) {
    this.accountSid = accountSid;
    return this;
  }

  /**
   * Get accountSid
   *
   * @return accountSid
   */
  @JsonProperty("account_sid")
  @Schema(description = "")
  public String getAccountSid() {
    return accountSid;
  }

  public void setAccountSid(String accountSid) {
    this.accountSid = accountSid;
  }

  public Notification apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

  /**
   * Get apiVersion
   *
   * @return apiVersion
   */
  @JsonProperty("api_version")
  @Schema(description = "")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public Notification callSid(String callSid) {
    this.callSid = callSid;
    return this;
  }

  /**
   * Get callSid
   *
   * @return callSid
   */
  @JsonProperty("call_sid")
  @Schema(description = "")
  public String getCallSid() {
    return callSid;
  }

  public void setCallSid(String callSid) {
    this.callSid = callSid;
  }

  public Notification dateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * Get dateCreated
   *
   * @return dateCreated
   */
  @JsonProperty("date_created")
  @Schema(description = "")
  public String getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
  }

  public Notification dateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
    return this;
  }

  /**
   * Get dateUpdated
   *
   * @return dateUpdated
   */
  @JsonProperty("date_updated")
  @Schema(description = "")
  public String getDateUpdated() {
    return dateUpdated;
  }

  public void setDateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
  }

  public Notification errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

  /**
   * Get errorCode
   *
   * @return errorCode
   */
  @JsonProperty("error_code")
  @Schema(description = "")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public Notification log(String log) {
    this.log = log;
    return this;
  }

  /**
   * Get log
   *
   * @return log
   */
  @JsonProperty("log")
  @Schema(description = "")
  public String getLog() {
    return log;
  }

  public void setLog(String log) {
    this.log = log;
  }

  public Notification messageDate(String messageDate) {
    this.messageDate = messageDate;
    return this;
  }

  /**
   * Get messageDate
   *
   * @return messageDate
   */
  @JsonProperty("message_date")
  @Schema(description = "")
  public String getMessageDate() {
    return messageDate;
  }

  public void setMessageDate(String messageDate) {
    this.messageDate = messageDate;
  }

  public Notification messageText(String messageText) {
    this.messageText = messageText;
    return this;
  }

  /**
   * Get messageText
   *
   * @return messageText
   */
  @JsonProperty("message_text")
  @Schema(description = "")
  public String getMessageText() {
    return messageText;
  }

  public void setMessageText(String messageText) {
    this.messageText = messageText;
  }

  public Notification moreInfo(String moreInfo) {
    this.moreInfo = moreInfo;
    return this;
  }

  /**
   * Get moreInfo
   *
   * @return moreInfo
   */
  @JsonProperty("more_info")
  @Schema(description = "")
  public String getMoreInfo() {
    return moreInfo;
  }

  public void setMoreInfo(String moreInfo) {
    this.moreInfo = moreInfo;
  }

  public Notification requestMethod(String requestMethod) {
    this.requestMethod = requestMethod;
    return this;
  }

  /**
   * Get requestMethod
   *
   * @return requestMethod
   */
  @JsonProperty("request_method")
  @Schema(description = "")
  public String getRequestMethod() {
    return requestMethod;
  }

  public void setRequestMethod(String requestMethod) {
    this.requestMethod = requestMethod;
  }

  public Notification requestUrl(String requestUrl) {
    this.requestUrl = requestUrl;
    return this;
  }

  /**
   * Get requestUrl
   *
   * @return requestUrl
   */
  @JsonProperty("request_url")
  @Schema(description = "")
  public String getRequestUrl() {
    return requestUrl;
  }

  public void setRequestUrl(String requestUrl) {
    this.requestUrl = requestUrl;
  }

  public Notification requestVariables(String requestVariables) {
    this.requestVariables = requestVariables;
    return this;
  }

  /**
   * Get requestVariables
   *
   * @return requestVariables
   */
  @JsonProperty("request_variables")
  @Schema(description = "")
  public String getRequestVariables() {
    return requestVariables;
  }

  public void setRequestVariables(String requestVariables) {
    this.requestVariables = requestVariables;
  }

  public Notification responseBody(String responseBody) {
    this.responseBody = responseBody;
    return this;
  }

  /**
   * Get responseBody
   *
   * @return responseBody
   */
  @JsonProperty("response_body")
  @Schema(description = "")
  public String getResponseBody() {
    return responseBody;
  }

  public void setResponseBody(String responseBody) {
    this.responseBody = responseBody;
  }

  public Notification responseHeaders(String responseHeaders) {
    this.responseHeaders = responseHeaders;
    return this;
  }

  /**
   * Get responseHeaders
   *
   * @return responseHeaders
   */
  @JsonProperty("response_headers")
  @Schema(description = "")
  public String getResponseHeaders() {
    return responseHeaders;
  }

  public void setResponseHeaders(String responseHeaders) {
    this.responseHeaders = responseHeaders;
  }

  public Notification sid(String sid) {
    this.sid = sid;
    return this;
  }

  /**
   * Get sid
   *
   * @return sid
   */
  @JsonProperty("sid")
  @Schema(description = "")
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public Notification uri(String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   *
   * @return uri
   */
  @JsonProperty("uri")
  @Schema(description = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Notification notification = (Notification) o;
    return Objects.equals(this.accountSid, notification.accountSid)
        && Objects.equals(this.apiVersion, notification.apiVersion)
        && Objects.equals(this.callSid, notification.callSid)
        && Objects.equals(this.dateCreated, notification.dateCreated)
        && Objects.equals(this.dateUpdated, notification.dateUpdated)
        && Objects.equals(this.errorCode, notification.errorCode)
        && Objects.equals(this.log, notification.log)
        && Objects.equals(this.messageDate, notification.messageDate)
        && Objects.equals(this.messageText, notification.messageText)
        && Objects.equals(this.moreInfo, notification.moreInfo)
        && Objects.equals(this.requestMethod, notification.requestMethod)
        && Objects.equals(this.requestUrl, notification.requestUrl)
        && Objects.equals(this.requestVariables, notification.requestVariables)
        && Objects.equals(this.responseBody, notification.responseBody)
        && Objects.equals(this.responseHeaders, notification.responseHeaders)
        && Objects.equals(this.sid, notification.sid)
        && Objects.equals(this.uri, notification.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        accountSid,
        apiVersion,
        callSid,
        dateCreated,
        dateUpdated,
        errorCode,
        log,
        messageDate,
        messageText,
        moreInfo,
        requestMethod,
        requestUrl,
        requestVariables,
        responseBody,
        responseHeaders,
        sid,
        uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Notification {\n");

    sb.append("    accountSid: ").append(toIndentedString(accountSid)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    callSid: ").append(toIndentedString(callSid)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateUpdated: ").append(toIndentedString(dateUpdated)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    log: ").append(toIndentedString(log)).append("\n");
    sb.append("    messageDate: ").append(toIndentedString(messageDate)).append("\n");
    sb.append("    messageText: ").append(toIndentedString(messageText)).append("\n");
    sb.append("    moreInfo: ").append(toIndentedString(moreInfo)).append("\n");
    sb.append("    requestMethod: ").append(toIndentedString(requestMethod)).append("\n");
    sb.append("    requestUrl: ").append(toIndentedString(requestUrl)).append("\n");
    sb.append("    requestVariables: ").append(toIndentedString(requestVariables)).append("\n");
    sb.append("    responseBody: ").append(toIndentedString(responseBody)).append("\n");
    sb.append("    responseHeaders: ").append(toIndentedString(responseHeaders)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
