/*
 * Twilio
 * Enabling phones, VoIP, and messaging to be embedded into web, desktop, and mobile software.
 *
 * OpenAPI spec version: 2010-04-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.xgp.hub.twilio.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import javax.validation.constraints.*;

/** OutCaller */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaJerseyDIServerCodegen",
    date = "2020-05-22T20:43:20.517+02:00[Europe/Paris]")
public class OutCaller {
  @JsonProperty("account_sid")
  private String accountSid = null;

  @JsonProperty("call_sid")
  private String callSid = null;

  @JsonProperty("friendly_name")
  private String friendlyName = null;

  @JsonProperty("phone_number")
  private String phoneNumber = null;

  @JsonProperty("validation_code")
  private Integer validationCode = null;

  public OutCaller accountSid(String accountSid) {
    this.accountSid = accountSid;
    return this;
  }

  /**
   * Get accountSid
   *
   * @return accountSid
   */
  @JsonProperty("account_sid")
  @Schema(description = "")
  public String getAccountSid() {
    return accountSid;
  }

  public void setAccountSid(String accountSid) {
    this.accountSid = accountSid;
  }

  public OutCaller callSid(String callSid) {
    this.callSid = callSid;
    return this;
  }

  /**
   * Get callSid
   *
   * @return callSid
   */
  @JsonProperty("call_sid")
  @Schema(description = "")
  public String getCallSid() {
    return callSid;
  }

  public void setCallSid(String callSid) {
    this.callSid = callSid;
  }

  public OutCaller friendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
    return this;
  }

  /**
   * Get friendlyName
   *
   * @return friendlyName
   */
  @JsonProperty("friendly_name")
  @Schema(description = "")
  public String getFriendlyName() {
    return friendlyName;
  }

  public void setFriendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
  }

  public OutCaller phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * Get phoneNumber
   *
   * @return phoneNumber
   */
  @JsonProperty("phone_number")
  @Schema(description = "")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public OutCaller validationCode(Integer validationCode) {
    this.validationCode = validationCode;
    return this;
  }

  /**
   * Get validationCode
   *
   * @return validationCode
   */
  @JsonProperty("validation_code")
  @Schema(description = "")
  public Integer getValidationCode() {
    return validationCode;
  }

  public void setValidationCode(Integer validationCode) {
    this.validationCode = validationCode;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutCaller outCaller = (OutCaller) o;
    return Objects.equals(this.accountSid, outCaller.accountSid)
        && Objects.equals(this.callSid, outCaller.callSid)
        && Objects.equals(this.friendlyName, outCaller.friendlyName)
        && Objects.equals(this.phoneNumber, outCaller.phoneNumber)
        && Objects.equals(this.validationCode, outCaller.validationCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountSid, callSid, friendlyName, phoneNumber, validationCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutCaller {\n");

    sb.append("    accountSid: ").append(toIndentedString(accountSid)).append("\n");
    sb.append("    callSid: ").append(toIndentedString(callSid)).append("\n");
    sb.append("    friendlyName: ").append(toIndentedString(friendlyName)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    validationCode: ").append(toIndentedString(validationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
