/*
 * Twilio
 * Enabling phones, VoIP, and messaging to be embedded into web, desktop, and mobile software.
 *
 * OpenAPI spec version: 2010-04-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.xgp.hub.twilio.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import javax.validation.constraints.*;

/** PhoneTollFreeNumbers */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaJerseyDIServerCodegen",
    date = "2020-05-22T20:43:20.517+02:00[Europe/Paris]")
public class PhoneTollFreeNumbers {
  @JsonProperty("available_phone_numbers")
  private java.util.List<Object> availablePhoneNumbers = null;

  @JsonProperty("uri")
  private String uri = null;

  public PhoneTollFreeNumbers availablePhoneNumbers(java.util.List<Object> availablePhoneNumbers) {
    this.availablePhoneNumbers = availablePhoneNumbers;
    return this;
  }

  public PhoneTollFreeNumbers addAvailablePhoneNumbersItem(Object availablePhoneNumbersItem) {
    if (this.availablePhoneNumbers == null) {
      this.availablePhoneNumbers = new java.util.ArrayList<>();
    }
    this.availablePhoneNumbers.add(availablePhoneNumbersItem);
    return this;
  }

  /**
   * Get availablePhoneNumbers
   *
   * @return availablePhoneNumbers
   */
  @JsonProperty("available_phone_numbers")
  @Schema(description = "")
  public java.util.List<Object> getAvailablePhoneNumbers() {
    return availablePhoneNumbers;
  }

  public void setAvailablePhoneNumbers(java.util.List<Object> availablePhoneNumbers) {
    this.availablePhoneNumbers = availablePhoneNumbers;
  }

  public PhoneTollFreeNumbers uri(String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   *
   * @return uri
   */
  @JsonProperty("uri")
  @Schema(description = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneTollFreeNumbers phoneTollFreeNumbers = (PhoneTollFreeNumbers) o;
    return Objects.equals(this.availablePhoneNumbers, phoneTollFreeNumbers.availablePhoneNumbers)
        && Objects.equals(this.uri, phoneTollFreeNumbers.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availablePhoneNumbers, uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneTollFreeNumbers {\n");

    sb.append("    availablePhoneNumbers: ")
        .append(toIndentedString(availablePhoneNumbers))
        .append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
