/*
 * Twilio
 * Enabling phones, VoIP, and messaging to be embedded into web, desktop, and mobile software.
 *
 * OpenAPI spec version: 2010-04-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.xgp.hub.twilio.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import javax.validation.constraints.*;

/** Queue */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaJerseyDIServerCodegen",
    date = "2020-05-22T20:43:20.517+02:00[Europe/Paris]")
public class Queue {
  @JsonProperty("average_wait_time")
  private Integer averageWaitTime = null;

  @JsonProperty("current_size")
  private Integer currentSize = null;

  @JsonProperty("date_created")
  private String dateCreated = null;

  @JsonProperty("date_updated")
  private String dateUpdated = null;

  @JsonProperty("friendly_name")
  private String friendlyName = null;

  @JsonProperty("max_size")
  private Integer maxSize = null;

  @JsonProperty("sid")
  private String sid = null;

  @JsonProperty("uri")
  private String uri = null;

  public Queue averageWaitTime(Integer averageWaitTime) {
    this.averageWaitTime = averageWaitTime;
    return this;
  }

  /**
   * Get averageWaitTime
   *
   * @return averageWaitTime
   */
  @JsonProperty("average_wait_time")
  @Schema(description = "")
  public Integer getAverageWaitTime() {
    return averageWaitTime;
  }

  public void setAverageWaitTime(Integer averageWaitTime) {
    this.averageWaitTime = averageWaitTime;
  }

  public Queue currentSize(Integer currentSize) {
    this.currentSize = currentSize;
    return this;
  }

  /**
   * Get currentSize
   *
   * @return currentSize
   */
  @JsonProperty("current_size")
  @Schema(description = "")
  public Integer getCurrentSize() {
    return currentSize;
  }

  public void setCurrentSize(Integer currentSize) {
    this.currentSize = currentSize;
  }

  public Queue dateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * Get dateCreated
   *
   * @return dateCreated
   */
  @JsonProperty("date_created")
  @Schema(description = "")
  public String getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
  }

  public Queue dateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
    return this;
  }

  /**
   * Get dateUpdated
   *
   * @return dateUpdated
   */
  @JsonProperty("date_updated")
  @Schema(description = "")
  public String getDateUpdated() {
    return dateUpdated;
  }

  public void setDateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
  }

  public Queue friendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
    return this;
  }

  /**
   * Get friendlyName
   *
   * @return friendlyName
   */
  @JsonProperty("friendly_name")
  @Schema(description = "")
  public String getFriendlyName() {
    return friendlyName;
  }

  public void setFriendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
  }

  public Queue maxSize(Integer maxSize) {
    this.maxSize = maxSize;
    return this;
  }

  /**
   * Get maxSize maximum: 1000
   *
   * @return maxSize
   */
  @JsonProperty("max_size")
  @Schema(description = "")
  @Max(1000)
  public Integer getMaxSize() {
    return maxSize;
  }

  public void setMaxSize(Integer maxSize) {
    this.maxSize = maxSize;
  }

  public Queue sid(String sid) {
    this.sid = sid;
    return this;
  }

  /**
   * Get sid
   *
   * @return sid
   */
  @JsonProperty("sid")
  @Schema(description = "")
  @Size(min = 34, max = 34)
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public Queue uri(String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   *
   * @return uri
   */
  @JsonProperty("uri")
  @Schema(description = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Queue queue = (Queue) o;
    return Objects.equals(this.averageWaitTime, queue.averageWaitTime)
        && Objects.equals(this.currentSize, queue.currentSize)
        && Objects.equals(this.dateCreated, queue.dateCreated)
        && Objects.equals(this.dateUpdated, queue.dateUpdated)
        && Objects.equals(this.friendlyName, queue.friendlyName)
        && Objects.equals(this.maxSize, queue.maxSize)
        && Objects.equals(this.sid, queue.sid)
        && Objects.equals(this.uri, queue.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        averageWaitTime, currentSize, dateCreated, dateUpdated, friendlyName, maxSize, sid, uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Queue {\n");

    sb.append("    averageWaitTime: ").append(toIndentedString(averageWaitTime)).append("\n");
    sb.append("    currentSize: ").append(toIndentedString(currentSize)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateUpdated: ").append(toIndentedString(dateUpdated)).append("\n");
    sb.append("    friendlyName: ").append(toIndentedString(friendlyName)).append("\n");
    sb.append("    maxSize: ").append(toIndentedString(maxSize)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
