/*
 * Twilio
 * Enabling phones, VoIP, and messaging to be embedded into web, desktop, and mobile software.
 *
 * OpenAPI spec version: 2010-04-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.xgp.hub.twilio.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import javax.validation.constraints.*;

/** ShortCode */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaJerseyDIServerCodegen",
    date = "2020-05-22T20:43:20.517+02:00[Europe/Paris]")
public class ShortCode {
  @JsonProperty("account_sid")
  private String accountSid = null;

  @JsonProperty("date_created")
  private String dateCreated = null;

  @JsonProperty("date_updated")
  private String dateUpdated = null;

  @JsonProperty("friendly_name")
  private String friendlyName = null;

  @JsonProperty("short_code")
  private String shortCode = null;

  @JsonProperty("sid")
  private String sid = null;

  @JsonProperty("sms_fallback_method")
  private String smsFallbackMethod = null;

  @JsonProperty("sms_fallback_url")
  private String smsFallbackUrl = null;

  @JsonProperty("sms_method")
  private String smsMethod = null;

  @JsonProperty("sms_url")
  private String smsUrl = null;

  @JsonProperty("uri")
  private String uri = null;

  public ShortCode accountSid(String accountSid) {
    this.accountSid = accountSid;
    return this;
  }

  /**
   * Get accountSid
   *
   * @return accountSid
   */
  @JsonProperty("account_sid")
  @Schema(description = "")
  public String getAccountSid() {
    return accountSid;
  }

  public void setAccountSid(String accountSid) {
    this.accountSid = accountSid;
  }

  public ShortCode dateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * Get dateCreated
   *
   * @return dateCreated
   */
  @JsonProperty("date_created")
  @Schema(description = "")
  public String getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
  }

  public ShortCode dateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
    return this;
  }

  /**
   * Get dateUpdated
   *
   * @return dateUpdated
   */
  @JsonProperty("date_updated")
  @Schema(description = "")
  public String getDateUpdated() {
    return dateUpdated;
  }

  public void setDateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
  }

  public ShortCode friendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
    return this;
  }

  /**
   * Get friendlyName
   *
   * @return friendlyName
   */
  @JsonProperty("friendly_name")
  @Schema(description = "")
  public String getFriendlyName() {
    return friendlyName;
  }

  public void setFriendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
  }

  public ShortCode shortCode(String shortCode) {
    this.shortCode = shortCode;
    return this;
  }

  /**
   * Get shortCode
   *
   * @return shortCode
   */
  @JsonProperty("short_code")
  @Schema(description = "")
  public String getShortCode() {
    return shortCode;
  }

  public void setShortCode(String shortCode) {
    this.shortCode = shortCode;
  }

  public ShortCode sid(String sid) {
    this.sid = sid;
    return this;
  }

  /**
   * Get sid
   *
   * @return sid
   */
  @JsonProperty("sid")
  @Schema(description = "")
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public ShortCode smsFallbackMethod(String smsFallbackMethod) {
    this.smsFallbackMethod = smsFallbackMethod;
    return this;
  }

  /**
   * Get smsFallbackMethod
   *
   * @return smsFallbackMethod
   */
  @JsonProperty("sms_fallback_method")
  @Schema(description = "")
  public String getSmsFallbackMethod() {
    return smsFallbackMethod;
  }

  public void setSmsFallbackMethod(String smsFallbackMethod) {
    this.smsFallbackMethod = smsFallbackMethod;
  }

  public ShortCode smsFallbackUrl(String smsFallbackUrl) {
    this.smsFallbackUrl = smsFallbackUrl;
    return this;
  }

  /**
   * Get smsFallbackUrl
   *
   * @return smsFallbackUrl
   */
  @JsonProperty("sms_fallback_url")
  @Schema(description = "")
  public String getSmsFallbackUrl() {
    return smsFallbackUrl;
  }

  public void setSmsFallbackUrl(String smsFallbackUrl) {
    this.smsFallbackUrl = smsFallbackUrl;
  }

  public ShortCode smsMethod(String smsMethod) {
    this.smsMethod = smsMethod;
    return this;
  }

  /**
   * Get smsMethod
   *
   * @return smsMethod
   */
  @JsonProperty("sms_method")
  @Schema(description = "")
  public String getSmsMethod() {
    return smsMethod;
  }

  public void setSmsMethod(String smsMethod) {
    this.smsMethod = smsMethod;
  }

  public ShortCode smsUrl(String smsUrl) {
    this.smsUrl = smsUrl;
    return this;
  }

  /**
   * Get smsUrl
   *
   * @return smsUrl
   */
  @JsonProperty("sms_url")
  @Schema(description = "")
  public String getSmsUrl() {
    return smsUrl;
  }

  public void setSmsUrl(String smsUrl) {
    this.smsUrl = smsUrl;
  }

  public ShortCode uri(String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   *
   * @return uri
   */
  @JsonProperty("uri")
  @Schema(description = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShortCode shortCode = (ShortCode) o;
    return Objects.equals(this.accountSid, shortCode.accountSid)
        && Objects.equals(this.dateCreated, shortCode.dateCreated)
        && Objects.equals(this.dateUpdated, shortCode.dateUpdated)
        && Objects.equals(this.friendlyName, shortCode.friendlyName)
        && Objects.equals(this.shortCode, shortCode.shortCode)
        && Objects.equals(this.sid, shortCode.sid)
        && Objects.equals(this.smsFallbackMethod, shortCode.smsFallbackMethod)
        && Objects.equals(this.smsFallbackUrl, shortCode.smsFallbackUrl)
        && Objects.equals(this.smsMethod, shortCode.smsMethod)
        && Objects.equals(this.smsUrl, shortCode.smsUrl)
        && Objects.equals(this.uri, shortCode.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        accountSid,
        dateCreated,
        dateUpdated,
        friendlyName,
        shortCode,
        sid,
        smsFallbackMethod,
        smsFallbackUrl,
        smsMethod,
        smsUrl,
        uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShortCode {\n");

    sb.append("    accountSid: ").append(toIndentedString(accountSid)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateUpdated: ").append(toIndentedString(dateUpdated)).append("\n");
    sb.append("    friendlyName: ").append(toIndentedString(friendlyName)).append("\n");
    sb.append("    shortCode: ").append(toIndentedString(shortCode)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    smsFallbackMethod: ").append(toIndentedString(smsFallbackMethod)).append("\n");
    sb.append("    smsFallbackUrl: ").append(toIndentedString(smsFallbackUrl)).append("\n");
    sb.append("    smsMethod: ").append(toIndentedString(smsMethod)).append("\n");
    sb.append("    smsUrl: ").append(toIndentedString(smsUrl)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
