/*
 * Twilio
 * Enabling phones, VoIP, and messaging to be embedded into web, desktop, and mobile software.
 *
 * OpenAPI spec version: 2010-04-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.xgp.hub.twilio.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import javax.validation.constraints.*;

/** Transcription */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaJerseyDIServerCodegen",
    date = "2020-05-22T20:43:20.517+02:00[Europe/Paris]")
public class Transcription {
  @JsonProperty("account_sid")
  private String accountSid = null;

  @JsonProperty("api_version")
  private String apiVersion = null;

  @JsonProperty("date_created")
  private String dateCreated = null;

  @JsonProperty("date_updated")
  private String dateUpdated = null;

  @JsonProperty("duration")
  private String duration = null;

  @JsonProperty("price")
  private String price = null;

  @JsonProperty("recording_sid")
  private String recordingSid = null;

  @JsonProperty("sid")
  private String sid = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("transcription_text")
  private String transcriptionText = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("uri")
  private String uri = null;

  public Transcription accountSid(String accountSid) {
    this.accountSid = accountSid;
    return this;
  }

  /**
   * Get accountSid
   *
   * @return accountSid
   */
  @JsonProperty("account_sid")
  @Schema(description = "")
  public String getAccountSid() {
    return accountSid;
  }

  public void setAccountSid(String accountSid) {
    this.accountSid = accountSid;
  }

  public Transcription apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

  /**
   * Get apiVersion
   *
   * @return apiVersion
   */
  @JsonProperty("api_version")
  @Schema(description = "")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public Transcription dateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * Get dateCreated
   *
   * @return dateCreated
   */
  @JsonProperty("date_created")
  @Schema(description = "")
  public String getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
  }

  public Transcription dateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
    return this;
  }

  /**
   * Get dateUpdated
   *
   * @return dateUpdated
   */
  @JsonProperty("date_updated")
  @Schema(description = "")
  public String getDateUpdated() {
    return dateUpdated;
  }

  public void setDateUpdated(String dateUpdated) {
    this.dateUpdated = dateUpdated;
  }

  public Transcription duration(String duration) {
    this.duration = duration;
    return this;
  }

  /**
   * Get duration
   *
   * @return duration
   */
  @JsonProperty("duration")
  @Schema(description = "")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public Transcription price(String price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   *
   * @return price
   */
  @JsonProperty("price")
  @Schema(description = "")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public Transcription recordingSid(String recordingSid) {
    this.recordingSid = recordingSid;
    return this;
  }

  /**
   * Get recordingSid
   *
   * @return recordingSid
   */
  @JsonProperty("recording_sid")
  @Schema(description = "")
  public String getRecordingSid() {
    return recordingSid;
  }

  public void setRecordingSid(String recordingSid) {
    this.recordingSid = recordingSid;
  }

  public Transcription sid(String sid) {
    this.sid = sid;
    return this;
  }

  /**
   * Get sid
   *
   * @return sid
   */
  @JsonProperty("sid")
  @Schema(description = "")
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public Transcription status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   *
   * @return status
   */
  @JsonProperty("status")
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Transcription transcriptionText(String transcriptionText) {
    this.transcriptionText = transcriptionText;
    return this;
  }

  /**
   * Get transcriptionText
   *
   * @return transcriptionText
   */
  @JsonProperty("transcription_text")
  @Schema(description = "")
  public String getTranscriptionText() {
    return transcriptionText;
  }

  public void setTranscriptionText(String transcriptionText) {
    this.transcriptionText = transcriptionText;
  }

  public Transcription type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   *
   * @return type
   */
  @JsonProperty("type")
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Transcription uri(String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   *
   * @return uri
   */
  @JsonProperty("uri")
  @Schema(description = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transcription transcription = (Transcription) o;
    return Objects.equals(this.accountSid, transcription.accountSid)
        && Objects.equals(this.apiVersion, transcription.apiVersion)
        && Objects.equals(this.dateCreated, transcription.dateCreated)
        && Objects.equals(this.dateUpdated, transcription.dateUpdated)
        && Objects.equals(this.duration, transcription.duration)
        && Objects.equals(this.price, transcription.price)
        && Objects.equals(this.recordingSid, transcription.recordingSid)
        && Objects.equals(this.sid, transcription.sid)
        && Objects.equals(this.status, transcription.status)
        && Objects.equals(this.transcriptionText, transcription.transcriptionText)
        && Objects.equals(this.type, transcription.type)
        && Objects.equals(this.uri, transcription.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        accountSid,
        apiVersion,
        dateCreated,
        dateUpdated,
        duration,
        price,
        recordingSid,
        sid,
        status,
        transcriptionText,
        type,
        uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transcription {\n");

    sb.append("    accountSid: ").append(toIndentedString(accountSid)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateUpdated: ").append(toIndentedString(dateUpdated)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    recordingSid: ").append(toIndentedString(recordingSid)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    transcriptionText: ").append(toIndentedString(transcriptionText)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
